server:
  host: localhost
  port: 8080
  static_assets_path: ./dist  # Path to static frontend assets (default: ./dist)

database:
  driver: sqlite  # sqlite, mysql, or postgres
  dsn: ./williams.db  # For SQLite: file path (foreign keys automatically enabled). For MySQL: user:pass@tcp(host:port)/dbname. For PostgreSQL: postgres://user:pass@host:port/dbname

auth:
  jwt_secret: change-this-secret-in-production-use-long-random-string
  first_user_is_admin: false  # If true, the first user to register will be assigned the admin role. Default: false (for security)

bills:
  payment_grace_days: 7  # Number of days before next due date to consider a recurring bill as paid
  maximum_billing_interval: 365  # Maximum number of days allowed for interval-based recurring bills

logging:
  level: info  # debug, info, warn, error, fatal, panic, disabled
  format: json  # json or console (console for human-readable output during development)

# Timezone for date/time storage and calculations
# Use IANA timezone format (e.g., "America/New_York", "America/Chicago", "UTC")
# Default: UTC
timezone: UTC
